#!/bin/bash
function install()
{
	ln -sf /opt/firefox/firefox   /usr/bin/firefox
	ln  -sf /opt/firefox/icons/mozicon128.png /usr/share/icons/mozicon.png
	echo "
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[zh_CN]=mozicon
Name[zh_CN]=firefox
Exec=firefox
Name=firefox
Icon=mozicon
Categories=Network;
" > /usr/share/applications/firefox.desktop
}

function uninstall()
{
	rm /usr/bin/firefox
	rm /usr/share/icons/mozicon.png
	rm /usr/share/applications/firefox.desktop
}

if [ $1 == "install" ];then
	install
else
	if [ $1 == "uninstall" ];then
		uninstall
	else
		echo "usage install_firefox [install|uninstall]"
	fi
fi
#!/usr/bin/env xdg-open

