#!/bin/bash
function start()
{
		sudo service php5-fpm start
		sudo service nginx start
}

function stop()
{
		sudo service php5-fpm stop
		sudo service nginx stop
}
function restart()
{
	sudo service php5-fpm restart
	sudo service nginx restart
}
case $1 in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: service phpnginx {start|stop|restart}"
		;;
esac
