#! /bin/sh
### BEGIN INIT INFO
# Provides:          pureftpd
# Required-Start:    networking
# Required-Stop:
# Default-Start:    S
# Default-Stop:      
# Short-Description: ftp daemon
# Description:
### END INIT INFO

CONFIG_FILE='/etc/pure-ftpd.conf'

. /lib/lsb/init-functions

do_stop () {
	# Message should end with a newline since kFreeBSD may
	# print more stuff (see #323749)
	log_action_msg "kill pureftpd"
	killall -9 pure-config.pl
}
do_start()
{
	log_action_msg "start pureftpd"	
	/usr/local/bin/pure-config.pl $CONFIG_FILE
}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload)
	do_stop
	do_start
	;;
  stop)
	do_stop
	;;
  *)
	echo "Usage: $0 start|stop|restart" >&2
	exit 3
	;;
esac
