#!/bin/bash
echo "goagent"
/opt/goagent/start_proxy.sh  >/dev/null 2>&1 &
echo "sogou proxy"
/opt/sogouproxy/sogouproxy  >/dev/null 2>&1 &
echo "shadowsocks proxy"
/usr/local/bin/sslocal -c /usr/local/bin/config.json >/dev/null 2>&1 &
